package javapractice;
import java.util.Scanner;
import java.util.Random;

class Game{
    private int number;  //only game class can access them (perfect encapsulation)
    private int numberofguesses;

    public Game(){
        Random rand = new Random();
        number = rand.nextInt(100)+1; //rand.nextInt(100) will generate a number between 0-99, we want in 1-100, so add 1
        numberofguesses = 0; //initialised the variable with 0, as user has not tried for even once
    }

    public int takeUserInput(){
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the number between 1 and 100 which you think might be generated by the computer: ");
        int guess = sc.nextInt();
        numberofguesses++; //user has tried guessing number once
        return guess; //will return the guessed number to the location from where it has been called
    }

    public boolean isCorrectNumber(int guess){  // method to check where the user has entered the correct number
        if(guess==number){
            System.out.println("Correct!You guessed the number in "+numberofguesses + " tries");
            return true;
        }
        else if(guess<number){
            System.out.println("Too low!!!! Please try again");

        }else{
            System.out.println("Too high!!! Please try again");
        }
        return false;

    }

        }
public class guessanumber {
    public static void main(String[] args) {
        Game g = new Game();
        boolean guessedCorrectly = false; //in the starting, keep it false as user has not tried anything yet
        //keep looping until correct guess
        while(!guessedCorrectly){ // until condition stays true, loop continues
            int userGuess = g.takeUserInput();
            guessedCorrectly = g.isCorrectNumber(userGuess);
        }
    }

}
